### DISCUSSION TITLE
Regarding APP_KEY on distributed pollers.

### DISCUSSION THREAD

**Discussion by oprietop** [librenms/docker#407] [Q&A]
Hi there!
I want to run librenms/redis/mariadb on a single host without any dispatcher/poller then use as many other physical machines for that job. That way i can keep the GUI/databases apart for their purposes and scale on pollers as needed.

Pollers seem to need the APP_KEY from the main instance to be able to talk the database and that variable needs to be in a /data/.env file in the poller, but there is no helper or automated way in the init scripts to create that file with these contents. I'm actually creating and mounting the .env file with the APP_KEY on every remote poller.

Is this approach correct or do i need a full fledged librenms docker service running alongside every distributed poller sharing the /data filesystem?
if I run multiple dispatcher/pollers on a single machine can they share the /data volume?

Thank you!

**Comment by murrant** [comment]
APP_KEY should be the same on all nodes of a cluster.

APP_KEY is accepted from the environment, so you can override whatever is in .env by passing it through docker.

**Reply by oprietop** [reply]
Thanks for the confirmation murrant!

Regarding the APP_KEY it  doesn't seem to work when the container is running as a dispatcher (SIDECAR_DISPATCHER=1):
```
librenms-poller_nr01_02-1  | >>
librenms-poller_nr01_02-1  | >> Sidecar dispatcher container detected
librenms-poller_nr01_02-1  | >>
librenms-poller_nr01_02-1  | Waiting 60s for database to be ready...
librenms-poller_nr01_02-1  | Database ready!
librenms-poller_nr01_02-1  | ERROR: /data/.env file does not exist. Please run the main container first
librenms-poller_nr01_02-1  | [cont-init.d] 05-svc-dispatcher.sh: exited 1.
```
This behaviour and the error is what it's making me doubt if the dispatcher can be run aside the main container.

**Reply by murrant** [reply]
The docker image creates .env.  Did you delete it manually?

**Reply by oprietop** [reply]
If I run the dispatcher alone (using the same reference readme code) it does not create the .env file. 
But currently I'm rereading the [documentation regarding the dispatchers](https://github.com/librenms/docker#dispatcher-service-container) and it clearly warns it needs a volume from a main instance.

My intention was to run the dispatcher only, without a main instance because i want to decouple services.
Currently i'm doing this as a workaround:

```
services:
  create-env:
    image: librenms/librenms:23.9.1
    volumes:
      - "./librenms:/data"
    container_name: create-env-1
    hostname: create-env-1
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "APP_KEY=${APP_KEY}" > /data/.env

  poller_01:
    image: librenms/librenms:23.9.1
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_TYPE=mysql"
      - "DB_HOST=${CORE_HOST}"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "NODE_ID=poller_01"
      - "DISPATCHER_NODE_ID=poller_01"
      - "SIDECAR_DISPATCHER=1"
      - "REDIS_HOST=${CORE_HOST}"
      - "RRDCACHED_SERVER=${CORE_HOST}:42217"
    restart: always
```
Everything seems to work but i don't know if something is breaking or will break if i'm not using an entire volume from a main instance.
