### ISSUE TITLE
/etc/msmtprc in librenms_msmtpd container is not populated by msmtp.env

### ISSUE THREAD

**Issue by jlixfeld** [librenms/docker#110]
### Behaviour

`/etc/msmtprc` in `librenms_msmtpd` container is not populated by `msmtp.env`

#### Steps to reproduce this issue

```
root@pgen:/home/jlixfeld# cd /opt/docker/librenms/librenms
root@pgen:/opt/docker/librenms/librenms# more msmtpd.env
# https://github.com/crazy-max/docker-msmtpd
SMTP_HOST=204.11.50.150
SMTP_PORT=25
SMTP_TLS=off
SMTP_STARTTLS=off
SMTP_TLS_CHECKCERT=off
SMTP_AUTH=off
SMTP_USER=foo
SMTP_PASSWORD=bar
SMTP_FROM=msmtpd@msmtpd.lab.snickers.org
root@pgen:/opt/docker/librenms/librenms# ls -al msmtpd.env
-rw-r--r-- 1 root root 223 Aug 13 16:58 msmtpd.env
(librenms) root@pgen:/opt/docker/librenms/librenms# docker ps | grep msmtp
cfeca872837a        crazymax/msmtpd:latest     "/init"                  19 hours ago        Up 16 hours (healthy)   2500/tcp                                               librenms_msmtpd
(librenms) root@pgen:/opt/docker/librenms/librenms# docker restart librenms_msmtpd
librenms_msmtpd
(librenms) root@pgen:/opt/docker/librenms/librenms# docker exec -it librenms_msmtpd cat /etc/msmtprc
account default
logfile -
syslog off
host smtp.gmail.com
port 587
tls on
tls_starttls on
tls_certcheck on
auth on
user foo
password bar
from foo@gmail.com
(librenms) root@pgen:/opt/docker/librenms/librenms# docker ps | grep msmtp
cfeca872837a        crazymax/msmtpd:latest     "/init"                  19 hours ago        Up 22 seconds (healthy)   2500/tcp                                               librenms_msmtpd
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

#### Expected behaviour

`/etc/msmtprc` should contain values from `msmtp.env`

#### Actual behaviour

`/etc/msmtprc` vales are not consistent with `msmtp.env`

### Configuration

* Docker version (type `docker --version`) : `Docker version 19.03.12, build 48a66213fe`
* Docker compose version if applicable (type `docker-compose --version`) : `docker-compose version 1.26.2, build unknown`
* Platform (Debian 9, Ubuntu 18.04, ...) : `Debian 10.5`
* System info (type `uname -a`) : `Linux pgen 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```
(librenms) root@pgen:/opt/docker/librenms/librenms# more docker-compose.yml
version: "3.5"

services:
  db:
    image: mariadb:10.4
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "./msmtpd.env"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - msmtpd
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    restart: always
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

```
(librenms) root@pgen:/opt/docker/librenms/librenms# cat librenms.env
TZ=EST5EDT

MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217

LIBRENMS_WEATHERMAP=true
LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

```
(librenms) root@pgen:/opt/docker/librenms/librenms# cat msmtpd.env
# https://github.com/crazy-max/docker-msmtpd
SMTP_HOST=204.11.50.150
SMTP_PORT=25
SMTP_TLS=off
SMTP_STARTTLS=off
SMTP_TLS_CHECKCERT=off
SMTP_AUTH=off
SMTP_USER=foo
SMTP_PASSWORD=bar
SMTP_FROM=msmtpd@msmtpd.lab.snickers.org
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

```
(librenms) root@pgen:/opt/docker/librenms/librenms# cat .env
TZ=EST5EDT
PUID=1000
PGID=1000

MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=asupersecretpassword
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

### Docker info

```
(librenms) root@pgen:/opt/docker/librenms/librenms# docker info
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 8
  Paused: 0
  Stopped: 2
 Images: 13
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-10-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.31GiB
 Name: pgen
 ID: AKLA:UCRH:ZTFB:WUPF:FLLF:NAW7:GAD6:EP5M:UBCH:QTZP:3YL4:RIIV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
(librenms) root@pgen:/opt/docker/librenms/librenms#
```

### Logs

```
(librenms) root@pgen:/opt/docker/librenms/librenms# docker stop librenms_msmtpd
librenms_msmtpd
(librenms) root@pgen:/opt/docker/librenms/librenms# docker -D -l debug start librenms_msmtpd
librenms_msmtpd
(librenms) root@pgen:/opt/docker/librenms/librenms# docker logs librenms_msmtpd
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
msmtp: authentication failed (method PLAIN)
Aug 13 20:42:03 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials y80sm3366113ilk.82 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials y80sm3366113ilk.82 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 20:42:55 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials y2sm3191306iow.30 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials y2sm3191306iow.30 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials d125sm3056673iof.32 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 20:43:44 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials d125sm3056673iof.32 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials c1sm3363425ilk.28 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 20:44:17 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials c1sm3363425ilk.28 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials h18sm3204106iow.16 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 20:59:49 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials h18sm3204106iow.16 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials b26sm1662600ill.31 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:15:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials b26sm1662600ill.31 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
Aug 13 21:15:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials j79sm3427180ilg.42 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials j79sm3427180ilg.42 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials j79sm3428377ilg.42 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:16:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials j79sm3428377ilg.42 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials o2sm3444551ili.83 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:16:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials o2sm3444551ili.83 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials y2sm3233354iow.30 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:16:02 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials y2sm3233354iow.30 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials x9sm3205728ior.12 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:25:00 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials x9sm3205728ior.12 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials v14sm3273153iln.76 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:25:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials v14sm3273153iln.76 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials c24sm3195375iom.46 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:25:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials c24sm3195375iom.46 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials c24sm3195387iom.46 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:25:01 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials c24sm3195387iom.46 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials e206sm3271785ioa.38 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:25:02 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials e206sm3271785ioa.38 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
Aug 13 21:32:07 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials k14sm3197280ion.17 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials k14sm3197280ion.17 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
msmtp: authentication failed (method PLAIN)
msmtp: server message: 535-5.7.8 Username and Password not accepted. Learn more at
msmtp: server message: 535 5.7.8  https://support.google.com/mail/?p=BadCredentials 17sm3392018ilg.16 - gsmtp
msmtp: could not send mail (account default from /etc/msmtprc)
Aug 13 21:32:22 host=smtp.gmail.com tls=on auth=on user=foo from=LibreNMS@librenms.lab.example.com recipients=jlixfeld@example.com smtpstatus=535 smtpmsg='535-5.7.8 Username and Password not accepted. Learn more at\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials 17sm3392018ilg.16 - gsmtp' errormsg='authentication failed (method PLAIN)' exitcode=EX_NOPERM
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-config.sh: executing...
Setting timezone to UTC...
Creating configuration...
[cont-init.d] 02-config.sh: exited 0.
[cont-init.d] 03-create-service.sh: executing...
[cont-init.d] 03-create-service.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
(librenms) root@pgen:/opt/docker/librenms/librenms#
```
