### ISSUE TITLE
Dispatcher: ERROR: Database migration not processed on bdlibrenms

### ISSUE THREAD

**Issue by xpatux** [librenms/docker#118]
Hi,

We have a swarm cluster running librenms, with a service called dispatcher with deploy mode global, so containers starts on every node on the cluster.

The problem is that there are two nodes (phisical servers) that fail to start the service with this error:

```
ERROR: Database migration not processed on bdlibrenms
```

The problem pops always on the same nodes.

We tried re-provisioning one of these nodes (remove from cluster, delete /var/lib/docker, reinstall Docker services and re-added to the cluster). Error persist.

Here is the output of validate.php while container is starting (waiting for db):

```bash
/opt/librenms # php validate.php 
====================================
Component | Version
--------- | -------
LibreNMS  | 1.66
DB Schema | 2020_05_30_162638_remove_mib_polling_tables (300)
PHP       | 7.3.20
Python    | 3.8.5
MySQL     | 5.7.23
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
/opt/librenms # 
```
this is the dispatcher part of the stack:
```yaml
  dispatcher:
    image: librenms/librenms:1.66
    hostname: "dispatcher-{{.Node.Hostname}}"
    deploy:
      placement:
        constraints:
          - node.labels.poller == true
      mode: global
      update_config:
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    depends_on:
      - bdlibrenms
      - memcached
      - rrdcached
      - redis
    volumes:
      - librenms:/data
      - /mnt/librenms/swarm/volumes/rrdcached:/data/rrd:ro
    networks:
      - default
      - influx_clients
    configs:
      - source: webui-update
        target: /data/config/update.php
      - source: bad_if
        target: /data/config/bad_if.php
      - source: snmp_com
        target: /data/config/snmp_com.php
      - source: comun_20191016
        target: /data/config/comun.php
    logging:
      driver: json-file
      options:
        max-size: 150m
    environment:
      - "TZ=America/Santiago"
      - "PUID=1000"
      - "PGID=1000"
      - "DB_HOST=bdlibrenms"
      - "DB_PASSWORD=*****"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher-{{.Node.Hostname}}"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
      - "RRDCACHED_HOST=rrdcached"
      - "MEMCACHED_HOST=memcached"
```
