### ISSUE TITLE
dispatcher not finding poller_cluser table, despite it being there.

### ISSUE THREAD

**Issue by evanrich** [librenms/docker#119]
I'm trying to get this working again using the new dispatcher side car, and having a weird issue.  

Librenms 1.66

running in kubernetes

When I start the pod (basically a clone of the docker compose), everything looks right, but then the dispatcher container exits with the following message:

```
 kubectl logs -f -n mon librenms2-0 -c dispatcher
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-fix-logs.sh: executing...
[cont-init.d] 00-fix-logs.sh: exited 0.
[cont-init.d] 01-fix-uidgid.sh: executing...
Switching to PGID 1001...
Switching to PUID 1001...
[cont-init.d] 01-fix-uidgid.sh: exited 0.
[cont-init.d] 02-fix-perms.sh: executing...
Fixing perms...
[cont-init.d] 02-fix-perms.sh: exited 0.
[cont-init.d] 03-config.sh: executing...
Setting timezone to America/Los_Angeles...
Setting PHP-FPM configuration...
Setting PHP INI configuration...
Setting OpCache configuration...
Setting Nginx configuration...
Updating SNMP community...
Initializing LibreNMS files / folders...
Setting LibreNMS configuration...
Fixing perms...
Checking additional Monitoring plugins...
[cont-init.d] 03-config.sh: exited 0.
[cont-init.d] 04-svc-main.sh: executing...
[cont-init.d] 04-svc-main.sh: exited 0.
[cont-init.d] 05-svc-dispatcher.sh: executing...
>>
>> Sidecar dispatcher container detected
>>
Waiting 60s for database to be ready...
Database ready!
ERROR: Table librenms.poller_cluster does not exist on mariadb.database.svc.cluster.local
[cont-init.d] 05-svc-dispatcher.sh: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

"table librenms.poller_cluster does not exist"   The problem is, it does:

I have an old database:

```
MariaDB [librenms]> desc poller_cluster;
+----------------+------------------+------+-----+---------+----------------+
| Field          | Type             | Null | Key | Default | Extra          |
+----------------+------------------+------+-----+---------+----------------+
| id             | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| node_id        | varchar(255)     | NO   | UNI | NULL    |                |
| poller_name    | varchar(255)     | NO   |     | NULL    |                |
| poller_version | varchar(255)     | NO   |     |         |                |
| poller_groups  | varchar(255)     | NO   |     |         |                |
| last_report    | datetime         | NO   |     | NULL    |                |
| master         | tinyint(1)       | NO   |     | NULL    |                |
+----------------+------------------+------+-----+---------+----------------+
7 rows in set (0.001 sec)

```
and a new one that im actually using:

```
MariaDB [librenms2]> desc poller_cluster
    -> ;
+-----------------------------+------------------+------+-----+---------+----------------+
| Field                       | Type             | Null | Key | Default | Extra          |
+-----------------------------+------------------+------+-----+---------+----------------+
| id                          | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| node_id                     | varchar(255)     | NO   | UNI | NULL    |                |
| poller_name                 | varchar(255)     | NO   |     | NULL    |                |
| poller_version              | varchar(255)     | NO   |     |         |                |
| poller_groups               | varchar(255)     | NO   |     |         |                |
| last_report                 | datetime         | NO   |     | NULL    |                |
| master                      | tinyint(1)       | NO   |     | NULL    |                |
| poller_enabled              | tinyint(4)       | YES  |     | NULL    |                |
| poller_frequency            | int(11)          | YES  |     | NULL    |                |
| poller_workers              | int(11)          | YES  |     | NULL    |                |
| poller_down_retry           | int(11)          | YES  |     | NULL    |                |
| discovery_enabled           | tinyint(4)       | YES  |     | NULL    |                |
| discovery_frequency         | int(11)          | YES  |     | NULL    |                |
| discovery_workers           | int(11)          | YES  |     | NULL    |                |
| services_enabled            | tinyint(4)       | YES  |     | NULL    |                |
| services_frequency          | int(11)          | YES  |     | NULL    |                |
| services_workers            | int(11)          | YES  |     | NULL    |                |
| billing_enabled             | tinyint(4)       | YES  |     | NULL    |                |
| billing_frequency           | int(11)          | YES  |     | NULL    |                |
| billing_calculate_frequency | int(11)          | YES  |     | NULL    |                |
| alerting_enabled            | tinyint(4)       | YES  |     | NULL    |                |
| alerting_frequency          | int(11)          | YES  |     | NULL    |                |
| ping_enabled                | tinyint(4)       | YES  |     | NULL    |                |
| ping_frequency              | int(11)          | YES  |     | NULL    |                |
| update_enabled              | tinyint(4)       | YES  |     | NULL    |                |
| update_frequency            | int(11)          | YES  |     | NULL    |                |
| loglevel                    | varchar(8)       | YES  |     | NULL    |                |
| watchdog_enabled            | tinyint(4)       | YES  |     | NULL    |                |
| watchdog_log                | varchar(255)     | YES  |     | NULL    |                |
+-----------------------------+------------------+------+-----+---------+----------------+

```

I've given the librenms user full permissions, and it doesnt' seem like anything is in the table:

```
MariaDB [librenms2]> select * from poller_cluster;
Empty set (0.001 sec)
```

my deployment file:

```
 containers:
      - name: librenms2
        image: librenms/librenms:1.66
        envFrom:
        - configMapRef:
            name: librenms-config
        volumeMounts:
        - name: dockerdata
          subPath: librenms2
          mountPath: /data
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: APP_KEY
          value: "base64:somebase64valuehere"
        - name: TZ
          value: 'America/Los_Angeles'
        - name: DB_HOST
          value: 'dbservername.database.svc.cluster.local'
        - name: DB_NAME
          value: 'librenms2'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_PASSWORD
        - name: MEMCACHED_HOST
          value: '127.0.0.1'
        ports:
        - name: librenms2
          containerPort: 8000
      - name: dispatcher
        image: librenms/librenms:1.66
        envFrom:
        - configMapRef:
            name: librenms-config
        volumeMounts:
        - name: dockerdata
          subPath: librenms2
          mountPath: /data
        env:
        - name: PUID
          value: '1001'
        - name: PGID
          value: '1001'
        - name: TZ
          value: 'America/Los_Angeles'
        - name: SIDECAR_DISPATCHER
          value: '1'
        - name: DISPATCHER_NODE_ID
          value: 'dispatcher1'
        - name: DB_HOST
          value: 'dbservername.database.svc.cluster.local'
        - name: DB_TIMEOUT
          value: '60'
        - name: MYSQL_DATABASE
          value: 'librenms2'
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_PASSWORD
        - name: DB_NAME
          value: 'librenms2'
        - name: REDIS_HOST
          value: 'localhost'
        - name: REDIS_PORT
          value: '6379'
        - name: REDIS_DB
          value: '0'
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: librenms
              key: LIBRENMS_PASSWORD
```

I've even tried putting these in a .env file and using that:

```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-config
  namespace: mon
data:
  DB_HOST: "dbserver.database.svc.cluster.local"
  DB_NAME: "librenms2"
  DB_PASSWORD: "librenms_password"
  DB_TIMEOUT: "60"
  DB_USER: "librenmsuser"
  LOG_IP_VAR: "remote_addr"
  MEMCACHED_HOST: "localhost"
  MEMCACHED_PORT: "11211"
  PGID: "1001"
  PUID: "1001"
  REAL_IP_HEADER: "X-Forwarded-For"
  TZ: "America/Los_Angeles"
```

It seems that despite these variables EVERYWHERE it still seems to want to look for something somewhere else.  What am i missing here?
