### ISSUE TITLE
Graphs randomly fail to load with RRDCached sidecar container

### ISSUE THREAD

**Issue by hugalafutro** [librenms/docker#124]
### Behaviour
Graphs load as red block randomly
#### Steps to reproduce this issue

1. use docker librenms install
2. refresh a page with any number of graphs (for me the most obvious culprits are the "Top Devices" widgets on dashboard, but it happens everywhere
3. observe as every refresh random number of the graphs doesn't load and look like red square, while some of the previously not loaded will load and display correct data

#### Expected behaviour

The graphs should all load

#### Actual behaviour

The graphs randomly do not load

### Configuration

* Docker version (type `docker --version`) : Docker version 19.03.12, build 48a66213fe
* Docker compose version if applicable (type `docker-compose --version`) : docker-compose version 1.25.0, build unknown
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 20.04
* System info (type `uname -a`) : Linux nms 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* dokcer-compose.yml and the .env files are literally the same as in the examples folder, I just changed port librenms listens on.

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 21
  Running: 20
  Paused: 0
  Stopped: 1
 Images: 19
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-47-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.661GiB
 Name: nms
 ID: ZYME:SMME:SOUR:BI62:XXOT:LR2H:THH4:FOAJ:IGJC:QXQZ:ZNW3:7RQE
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

### Logs

```
Nothing in any of librenms containers logs indicate any error.
```
Validate:
```
====================================
Component | Version
--------- | -------
LibreNMS  | 1.66
DB Schema | 2020_08_28_212054_drop_uptime_column_outages (173)
PHP       | 7.3.21
Python    | 3.8.5
MySQL     | 10.4.14-MariaDB-1:10.4.14+maria~focal
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

There is also a discussion with some screenshots @ https://community.librenms.org/t/problems-with-graphs-red-only-missing-error-drawing-graph/10279

**Comment by Munzy** [comment]
I face this issue as well.

**Comment by rigocalin** [comment]
Same here.

**Comment by Minocula** [comment]
Yesterday I have also installend a fresh librenms docker environment with docker compose. no errors. Installation Validation fine (same as by @hugalafutro ). I am sure, there is missing something. 

![librenms poller status](https://user-images.githubusercontent.com/63090608/93429185-0b4a0b80-f8c1-11ea-9b19-7438f6321a0c.PNG)

Example of no data device:
![librenms no graph data example](https://user-images.githubusercontent.com/63090608/93429228-1a30be00-f8c1-11ea-8d25-248751b51b02.PNG)

**Comment by nathanaelpearson** [comment]
HI

I have the same issue with application graphs (NTP Server, NTP Client) being impacted.
This is in a non-Docker environment on Ubuntu.
Happy to add specific details if that helps.

Kind regards

**Comment by hugalafutro** [comment]
@nathanaelpearson that is strange as I run both docker and normal install on ubuntu 20 and this issue only happens on docker for me. The normal install is pretty much flawless.

After updating the docker install to 1.68 the graphs now seem to load correctly elsewhere apart from in the Top Devices widget in dashboard (strangely enough, not for Top Devices - Poller).

English is not my native language - I'm having trouble describing exactly what happens so I made a small video (i.e. I do not think this is the same issue as @Minocula has - your issue seems to be the docker can't dns resolve the hosts, I had to add some hosts to /etc/hosts on the docker machine myself, funnily enough the docker machine itself too which might be indicative of some underlying network issue, but I digress):
[](https://www.youtube.com/watch?v=nVg_6TANP04)

In 1.66 docker install this same would happen on any screen with many detail graphs such as smart application or ports, but the missing graphs would be blank and on reloading the page they'd load and random set of others would become blank. This is no longer happening to me.

**Comment by nathanaelpearson** [comment]
Hi
This is what i'm getting but only for apps:-

![image](https://user-images.githubusercontent.com/68738162/94820656-9f0af400-03f8-11eb-9117-72d806ffd0c6.png)

When you click on a mini-graph I get the following:
![image](https://user-images.githubusercontent.com/68738162/94820904-e2fdf900-03f8-11eb-86e8-2011c568c6b4.png)

From your description I wonder if these are two different issues with the same symptoms.

Kind regards

**Comment by hugalafutro** [comment]
@nathanaelpearson I think your issue is with application not with graph drawing, are you sure the data is getting to nms and the app works? Because in your first picture the graph drawing works as it draws the axis and numbers, but the app either didn't write any data into the rrd or the php responsible for interpreting it has trouble (recently from apps I use pi-hole, apcupsd and unbound app had similar issues).

The red mini-graphs then make sense as there is no long-term data to create the graph - iirc, this is exactly how it behaves when autodetecting/manually enabling an app, but before it populates its RRD with data from polling cycle, which ios a state you're perpetually locked in if there is trouble with getting the data from the host into the rrd.

**Comment by crazy-max** [comment]
@hugalafutro 

> After updating the docker install to 1.68 the graphs now seem to load correctly elsewhere apart from in the Top Devices widgets in dashboard (strangely enough, not for Top Devices - Poller).

I think this has been fixed in 1.68 through librenms/librenms#12152

**Comment by hugalafutro** [comment]
That's my pr (2nd ever lol) but that was only for unbound application. the youtube video I posted was taken from docker install updated to 1.68, where the unbound app started correctly working, but the graphs in dashboard randomly load as red. Also the mini graphs as in @nathanaelpearson picture (the 6h 24h 48h One Week Two Week graphs)

**Comment by crazy-max** [comment]
@hugalafutro Ok I watched your video.

> I had to add some hosts to /etc/hosts on the docker machine myself, funnily enough the docker machine itself too which might be indicative of some underlying network issue, but I digress):

Wonder what host you have added in your hosts file to make it work? Maybe rrdcached should be embedded in the main Docker image to avoid this kind of issue :thinking:. This is the only difference I can see compared to a classic installation.

**Comment by hugalafutro** [comment]
nms is the host on which the docker runs and the librenms installed in the docker on it would not snmp discover the nms host until I added `127.0.1.1 nms` into /etc/hosts (No idea why that particular address, but that made it work, I believe that was the ip of nms.lan when I pinged it from inside the docker container).

so now my /etc/hosts looks like:
127.0.0.1 localhost
127.0.1.1 nms

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

I can't reboot the host atm and test, but iirc adding nms to the 127.0.0.1 line worked too, but caused other issue I can't remember.

I'm not really sure whether it's related as I'm not all that technologically proficient ;)

**Comment by setiseta** [comment]
@crazy-max on my own docker image, i have integrated rrdcached in main librenms, and used the socket connection. there all is good, since i try to use official docker everywere, i changed a test installation to this one. here i get also those "red blocks".
as far as i have seen it is because of the network connection to rrdcache, there is something not working optimal, maybe some flushing?
at least i think this is an rrdcached issue, but can be fixed if used with sockets. maybe we could share the socket and try to use this connection?

**Comment by nathanaelpearson** [comment]
> @hugalafutro
> 
> After updating the docker install to 1.68 the graphs now seem to load correctly elsewhere apart from in the Top Devices widgets in dashboard (strangely enough, not for Top Devices - Poller).
> 
> I think this has been fixed in 1.68 through librenms/librenms#12152

HI
Thanks for all the update.
I've checked other app polling and this only seems to affect NTP server and NTP client graphs for me.
That issue remains after the last update.

Kind regards

**Comment by setiseta** [comment]
I've tested to share the rrdcached socket. It felt slightly better, but I also get the red blocks.
I can only get rid of them if I disable rrdcached in the docker setup in librenms.env

**Comment by hugalafutro** [comment]
> I've tested to share the rrdcached socket. It felt slightly better, but I also get the red blocks.
> I can only get rid of them if I disable rrdcached in the docker setup in librenms.env

Disabling rrdcached in the .env file worked here too. I assume it might be an issue for large nms installs, but I with my less than 20 devices I notice no difference in speed and the damn red blocks are finally gone first time since I've converted to docker install.

Thanks for the workaround!

**Comment by hugalafutro** [comment]
I just tried the latest image, removed the old rrdcached variables in `librenms.env` and added the new one, rebuild the container and the random red block on graphs are still there :(

Disabling rrdcached by commenting out the line in `librenms.env` seems still the only way to get rid of them.

**As someone who only monitors his home network with <20 devices do I really need rrdcached?** Perhaps a placebo effect, but I feel the whole thing is snappier without rrdcached.

For reference my `docker-compose.yml`:

```
version: "3.5"

services:
  db:
    image: mariadb:10.4
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: unless-stopped

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: unless-stopped

  redis:
    image: redis:5.0-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: unless-stopped

#  rrdcached:
#    image: crazymax/rrdcached
#    container_name: librenms_rrdcached
#    volumes:
#      - "./librenms/rrd:/data/db"
#      - "./rrd-journal:/data/journal"
#    environment:
#      - "TZ=${TZ}"
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#      - "LOG_LEVEL=LOG_INFO"
#      - "WRITE_TIMEOUT=1800"
#      - "WRITE_JITTER=1800"
#      - "WRITE_THREADS=4"
#      - "FLUSH_DEAD_DATA_INTERVAL=3600"
#    restart: unless-stopped

#  msmtpd:
#    image: crazymax/msmtpd:latest
#    container_name: librenms_msmtpd
#    env_file:
#      - "./msmtpd.env"
#    restart: unless-stopped

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    ports:
      - target: 8000
        published: 8161
        protocol: tcp
    depends_on:
      - db
      - memcached
#      - rrdcached
#      - msmtpd
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: unless-stopped

  dispatcher:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"
      - "REDIS_DB=0"
      - "SIDECAR_DISPATCHER=1"
    restart: unless-stopped

#  syslogng:
#    image: librenms/librenms:latest
#    container_name: librenms_syslogng
#    hostname: librenms-syslogng
#    depends_on:
#      - librenms
#    ports:
#      - target: 514
#        published: 514
#        protocol: tcp
#      - target: 514
#        published: 514
#        protocol: udp
#    volumes:
#      - "./librenms:/data"
#    env_file:
#      - "./librenms.env"
#    environment:
#      - "TZ=${TZ}"
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#      - "DB_HOST=db"
#      - "DB_NAME=${MYSQL_DATABASE}"
#      - "DB_USER=${MYSQL_USER}"
#      - "DB_PASSWORD=${MYSQL_PASSWORD}"
#      - "DB_TIMEOUT=60"
#      - "SIDECAR_SYSLOGNG=1"
#    restart: unless-stopped

```
notes:
msmtpd is commented out because a) I couldn't get it to work and b) I use telegram notifications
syslogng is commented out because I run graylog in different container and collect all computers system logs there and integrate that into librenms
