### ISSUE TITLE
dispatcher ERROR: REDIS_HOST or REDIS_SENTINEL must be defined

### ISSUE THREAD

**Issue by karlshea** [librenms/docker#151]
### Behaviour

This is on the edge image, latest works.

#### Steps to reproduce this issue

1. Start the dispatcher container
2. View logs

#### Expected behaviour

Dispatcher works

#### Actual behaviour

`ERROR: REDIS_HOST or REDIS_SENTINEL must be defined`. I'm not using Redis. Adding an empty `REDIS_HOST=` also doesn't work.

### Configuration

* Docker version (type `docker --version`) : 19.03.14, build 5eb3275d40
* Docker compose version if applicable (type `docker-compose --version`) : 1.27.4, build 40524192
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04
* System info (type `uname -a`) : Linux citywall 4.15.0-124-generic #127-Ubuntu SMP Fri Nov 6 10:54:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```
version: '3.5'

services:
  traefik:
    image: traefik:2.3
    container_name: traefik
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--log=true"
      - "--log.level=INFO"
      - "--entrypoints.http=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.http.http.redirections.entrypoint.to=https"
      - "--entrypoints.http.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.https=true"
      - "--entrypoints.https.address=:443"
      - "--certificatesresolvers.letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesresolvers.letsencrypt.acme.email=${AWS_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=route53"

      # Don't check propagation because of internal split DNS (record won't exist internally)
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.disablepropagationcheck=true"

      - "--providers.docker"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "${IP_ADDRESS}:80:80"
      - "${IP_ADDRESS}:443:443"
    environment:
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "AWS_HOSTED_ZONE_ID=${AWS_HOSTED_ZONE_ID}"
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.4
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  librenms:
    image: librenms/librenms:edge
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
    volumes:
      - "./librenms:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.entrypoints=https"
      - "traefik.http.routers.librenms.rule=Host(`xxxx`)"
      - "traefik.http.routers.librenms.tls=true"
      - "traefik.http.routers.librenms.tls.certresolver=letsencrypt"
      - "traefik.http.routers.librenms.tls.domains[0].main=xxxx"
      - "traefik.http.services.librenms.loadbalancer.server.port=8000"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher:
    image: librenms/librenms:edge
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
    restart: always
```

.env
```
TZ=America/Chicago
PUID=999 # librenms
PGID=999 # librenms

IP_ADDRESS=192.168.10.7

MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=librenms

AWS_EMAIL=xxx
AWS_ACCESS_KEY_ID=xxx
AWS_SECRET_ACCESS_KEY=xxx
AWS_HOSTED_ZONE_ID=xxx
```

librenms.env
```
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
#LOG_IP_VAR=http_x_forwarded_for # traefik
LOG_IP_VAR=remote_addr # bare

LIBRENMS_SNMP_COMMUNITY=public
#MEMCACHED_HOST=memcached
#MEMCACHED_PORT=11211

LIBRENMS_WEATHERMAP=false
LIBRENMS_WEATHERMAP_SCHEDULE=*/5 * * * *
```

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 14
 Server Version: 19.03.14
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: ea765aba0d05254012b0b9e595e995c09186427f
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-124-generic
 Operating System: Ubuntu 18.04.5 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.54GiB
 Name: citywall
 ID: DTZF:I5E4:WY2R:OALB:UMOP:HCBU:HKRA:HOIS:5OZD:WF4I:4O3F:SBCP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

### Logs

```
dispatcher_1  | [cont-init.d] 02-fix-perms.sh: executing...
dispatcher_1  | Fixing perms...
dispatcher_1  | [cont-init.d] 02-fix-perms.sh: exited 0.
dispatcher_1  | [cont-init.d] 03-config.sh: executing...
dispatcher_1  | Setting timezone to America/Chicago...
dispatcher_1  | Setting PHP-FPM configuration...
dispatcher_1  | Setting PHP INI configuration...
dispatcher_1  | Setting OpCache configuration...
dispatcher_1  | Setting Nginx configuration...
dispatcher_1  | Updating SNMP community...
dispatcher_1  | Initializing LibreNMS files / folders...
dispatcher_1  | Setting LibreNMS configuration...
dispatcher_1  | Fixing perms...
dispatcher_1  | Checking additional Monitoring plugins...
dispatcher_1  | Checking alert templates...
dispatcher_1  | [cont-init.d] 03-config.sh: exited 0.
dispatcher_1  | [cont-init.d] 04-svc-main.sh: executing...
dispatcher_1  | [cont-init.d] 04-svc-main.sh: exited 0.
dispatcher_1  | [cont-init.d] 05-svc-dispatcher.sh: executing...
dispatcher_1  | >>
dispatcher_1  | >> Sidecar dispatcher container detected
dispatcher_1  | >>
dispatcher_1  | Waiting 60s for database to be ready...
dispatcher_1  | Database ready!
dispatcher_1  | NODE_ID: dispatcher1
dispatcher_1  | ERROR: REDIS_HOST or REDIS_SENTINEL must be defined
dispatcher_1  | [cont-init.d] 05-svc-dispatcher.sh: exited 1.
dispatcher_1  | [cont-finish.d] executing container finish scripts...
dispatcher_1  | [cont-finish.d] done.
dispatcher_1  | [s6-finish] waiting for services.
dispatcher_1  | [s6-finish] sending all processes the TERM signal.
dispatcher_1  | [s6-finish] sending all processes the KILL signal and exiting.
```
