### ISSUE TITLE
enabling SMTP does not work

### ISSUE THREAD

**Issue by jyipks** [librenms/docker#20]
after setting up the .env file and running your docker compose, going to 
settinsg >global settings > alert settings> email options >and choosing SMTP, i enter the from email address, and create an alert transport for email and do a test, it fails.
I leave smtp host as localhost(default), port 25. I also tried putting the smtp server in there directly and still fails.

What are the proper steps on enabling SMTP? I have the postfix container running, but is that required.

Thanks

**Comment by murrant** [comment]
You should deliver email to an actual email server otherwise it might get bloocked by spam filtering.

**Comment by crazy-max** [comment]
@jyipks Like @murrant said, you have to set up a SMTP server. You could add a smtp docker service like [juanluisbaptiste/docker-postfix](https://github.com/juanluisbaptiste/docker-postfix) in your compose :

```
services:
  postfix:
    image: juanluisbaptiste/postfix:latest
    env_file:
      - credentials-smtp.env
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
```

And edit your mail settings like this (as a quick example) :

![image](https://user-images.githubusercontent.com/1951866/53122622-4d7d6080-3557-11e9-8542-a0e80c93b218.png)
