### ISSUE TITLE
/opt/librenms/snmp-scan.php does not work when running in Docker container

### ISSUE THREAD

**Issue by mountaindude** [librenms/docker#25]
Looks like #7 is not fixed after all.

I get this error when setting up a fresh LibreNMS stack using Docker.
Something is missing in the container.

```bash
goran@sm1:/opt/docker/container/librenms$ docker exec -it librenms bash
bash-4.4# /opt/librenms/snmp-scan.php -r 192.168.1.0/24
bash: /opt/librenms/snmp-scan.php: No such file or directory
bash-4.4# /opt/librenms/snmp-scan.py -r 192.168.1.0/24
Could not import ipaddress module.  Please install python-ipaddress or use python3 to run this script
Debian/Ubuntu: apt install python-ipaddress
RHEL/CentOS: yum install python-ipaddress
bash-4.4# 
```

Installed python versions in the container:

```bash
bash-4.4# python --version
Python 2.7.15
bash-4.4# python3 --version
Python 3.6.8
bash-4.4#
```

My docker-compose is pretty much straight from the Github example:

```yaml
  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    domainname: ptarmiganlabs.net
    hostname: librenms
    depends_on:
      - db
      - memcached
      - rrdcached
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always
```
