### ISSUE TITLE
Give example docker swarm deployment

### ISSUE THREAD

**Issue by crazy-max** [librenms/docker#3]
By @jsenecal (crazy-max/docker-librenms#1)

> It would be nice if you added an example docker-compose.yml suitable for docker in swarm mode.
> 
> This should also provide separate web and poller using rrdcache and memcache for rrd storage and poller state exchange (already available, though I cannot figure how you are configuring them in the "app" service).
> 
> I'm currently running something like this [docker-compose.yml file](https://gist.github.com/jsenecal/ca255c2734d1f18b9eaeaf63037e3904) with most of the librenms stuff from the [other available image](https://github.com/jarischaefer/docker-librenms)

**Comment by sk4mi** [comment]
Possible to add example for docker kubernetes deployment ?

**Comment by arbaldin** [comment]
A swarm (and/or kubernetes) with how to scale the dispatcher (and/or cron) sidecar would be great!

**Comment by mzac** [comment]
Here is my k3s example.  It includes the deployments, services and an ingress.

Note that I am running my MySQL externally on my NAS which is why I don't have a MySQL container.  I did this because when trying to use my NAS as a data store for MySQL gave me file lock errors.  Installing the MySQL service on my NAS made things easier.

Also, all my data stores are on my NAS (mounted with NFS) which is why there are nfs-fixers to fix the permissions on the file system.

```
# --------------------------------------------------------------------------------
# Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: librenms

# --------------------------------------------------------------------------------
# Memcached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
      - name: memcached
        image: memcached:alpine
        imagePullPolicy: IfNotPresent

# --------------------------------------------------------------------------------
# Redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:5.0-alpine
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Montreal

# --------------------------------------------------------------------------------
# RRDCached
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rrdcached
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rrdcached
  template:
    metadata:
      labels:
        app: rrdcached
    spec:
      initContainers:
        - name: nfs-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: rrdcached-main
            mountPath: /nfs
          command:
          - sh
          - -c
          - (chmod 0775 /nfs; chown -R 1000:1000 /nfs)
      containers:
      - name: rrdcached
        image: crazymax/rrdcached
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Montreal
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: LOG_LEVEL
          value: LOG_INFO
        - name: WRITE_TIMEOUT
          value: "1800"
        - name: WRITE_JITTER
          value: "1800"
        - name: WRITE_THREADS
          value: "4"
        - name: FLUSH_DEAD_DATA_INTERVAL
          value: "3600"
        volumeMounts:
        - name: rrdcached-db
          mountPath: /data/db
        - name: rrdcached-journal
          mountPath: /data/journal
      volumes:
      - name: rrdcached-main
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/rrdcached
      - name: rrdcached-db
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/rrdcached/db
      - name: rrdcached-journal
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/rrdcached/journal

# --------------------------------------------------------------------------------
# Config Map
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: librenms-config
  namespace: librenms
data:
  MYSQL_DATABASE: librenms
  MYSQL_USERNAME: librenms
  MYSQL_PASSWORD: librenms
  MYSQL_SERVER: 192.168.0.6

# --------------------------------------------------------------------------------
# LibreNMS
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librenms
  namespace: librenms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librenms
  template:
    metadata:
      labels:
        app: librenms
    spec:
      initContainers:
        - name: nfs-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: librenms-data
            mountPath: /nfs
          command:
          - sh
          - -c
          - (chmod 0775 /nfs; chown -R 1000:1000 /nfs)
      containers:
      - name: librenms
        image: librenms/librenms:1.65
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Montreal
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_PASSWORD
        - name: DB_TIMEOUT
          value: "60"
        - name: MEMCACHED_HOST
          value: memcached
        - name: MEMCACHED_PORT
          value: "11211"
        - name: RRDCACHED_HOST
          value: rrdcached
        - name: RRDCACHED_PORT
          value: "42217"
        - name: REAL_IP_HEADER
          value: "X-Forwarded-For"
        - name: LOG_IP_VAR
          value: "remote_addr"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/librenms-data

# --------------------------------------------------------------------------------
# LibreNMS Dispatcher
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: librenms-dispatcher
  namespace: librenms
spec:
  serviceName: librenms-dispatcher
  replicas: 1
  selector:
    matchLabels:
      app: librenms-dispatcher
  template:
    metadata:
      labels:
        app: librenms-dispatcher
    spec:
      initContainers:
        - name: nfs-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: librenms-data
            mountPath: /nfs
          command:
          - sh
          - -c
          - (chmod 0775 /nfs; chown -R 1000:1000 /nfs)
      containers:
      - name: librenms-dispatcher
        image: librenms/librenms:1.65
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Montreal
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_PASSWORD
        - name: DB_TIMEOUT
          value: "60"
        - name: DISPATCHER_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: SIDECAR_DISPATCHER
          value: "1"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      volumes:
      - name: librenms-data
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/librenms-data

# --------------------------------------------------------------------------------
# Service - memcached
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: librenms
spec:
  ports:
  - name: memcached
    targetPort: 11211
    port: 11211
  selector:
    app: memcached

# --------------------------------------------------------------------------------
# Service - redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: librenms
spec:
  ports:
  - name: redis
    targetPort: 6379
    port: 6379
  selector:
    app: redis

# --------------------------------------------------------------------------------
# Service - rrdcached
---
apiVersion: v1
kind: Service
metadata:
  name: rrdcached
  namespace: librenms
spec:
  ports:
  - name: rrdcached
    targetPort: 42217
    port: 42217
  selector:
    app: rrdcached

# --------------------------------------------------------------------------------
# Service - LibreNMS
---
apiVersion: v1
kind: Service
metadata:
  name: librenms
  namespace: librenms
  annotations:
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
spec:
  ports:
  - name: http
    targetPort: 8000
    port: 80
  selector:
    app: librenms

# --------------------------------------------------------------------------------
# Ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: librenms-ingress
  namespace: librenms
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/frontend-entry-points: http
spec:
  rules:
  - host: librenms.lab.local
    http:
      paths:
      - path: /
        backend:
          serviceName: librenms
          servicePort: http
```
