### ISSUE TITLE
librenms container is not updating

### ISSUE THREAD

**Issue by radokristof** [librenms/docker#394]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/librenms/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The librenms container is not updating to the latest version, even though I'm using "latest" tag

### Expected behaviour

Should have the same version number as the image version.

### Actual behaviour

Version reported by librenms is much older than image version:
Current image version: [23.8.2](https://hub.docker.com/layers/librenms/librenms/23.8.2/images/sha256-be18fb9ffd3aa2816e01ea958093f23e12ec4df5d15f931fbac62184aa4d1793?context=explore)

LibreNMS version (GUI and CLI tools also show this): 22.7.0

### Steps to reproduce

Not sure how to reproduce this. It is a fairly old install (around 3 years old) I always updated it with `docker compose pull` command.

### Docker info

```text
Client: Docker Engine - Community
 Version:    24.0.6
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.21.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 28
  Running: 27
  Paused: 0
  Stopped: 1
 Images: 26
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 5.15.0-1041-kvm
 Operating System: Ubuntu 22.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 13.67GiB
 Name: marinero-m02
 ID: KOYP:2W5C:NAC7:7CD3:SLFN:B7VM:6ITH:SKWT:2NDT:H2CW:VI6O:3R5A
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Default Address Pools:
   Base: 192.168.0.0/16, Size: 24
```

### Docker Compose config

```yaml
Relevant `docker-compose.yml` section:

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - "./librenms:/data"
      - "./opt:/opt/librenms"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=${MYSQL_HOST}"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=${MYSQL_TIMEOUT}"
      - "LISTEN_IPV6=false"
      - "LIBRENMS_BASE_URL=network.marinero.cloud"
      - "REAL_IP_FROM=192.168.0.0/16"
      - "LOG_IP_VAR=http_x_forwarded_for"
    restart: always
```

### Logs

```text
-
```

### Additional info

I have tried downgrading and then upgrading again from different versions, but no change
