### ISSUE TITLE
Auto-discovery not running automatically, works manually 

### ISSUE THREAD

**Issue by Aerosyth** [librenms/docker#444]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/librenms/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

So I have LibreNMS stood up using the example with some additional dispatchers added. I have enabled discovery by IP, added my networks, and exclusions, and also ensured that the settings replicated to my dispatchers by going into the shell and using the "lnms config:get" command. Everything seems to be set correctly.

I can exec into my main LibreNMS container, and run the "snmp-scan.py" script and it runs absolutely fine with no errors. It added about 5 devices before I terminated the script (I would like to see the rest be added by the automatic scan interval to ensure function). This is great, but from my understanding, this would run automatically every 6 hours. I reduced the time to 1 hour for testing purposes because I didn't want to wait 6 hours to ensure if it was working or not. Is there an environment variable or something I'm missing?

In the main LibreNMS container, I notice there are 3 cron jobs under the librenms user that don't seem to be calling on the wrapper script or the SNMP scan script. This may be irrelevant, but I just figured it was worth sharing.

Thank you in advance for any help/guidance. 

### Expected behaviour

SNMP scan for specified networks executes every 6 hours (or other time cycle specified)

### Actual behaviour

SNMP scan can be manually run, but never executes on its own

### Steps to reproduce

1. Configure test LibreNMS environment with rrdcached
2. Enable discovery by IP
3. List included networks that are desired to be scanned

### Docker info

```text
Client:
 Version:    25.0.5
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.12.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.23.3
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 14
  Running: 14
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 25.0.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 4e1fe7492b9df85914c389d1f15a3ceedbb280ac
 runc version: 51d5e94601ceffbbd85688df1c928ecccbfa4685
 init version:
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.6.31-0-virt
 Operating System: Alpine Linux v3.19
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.79GiB
 Name: librenms1
 ID: 10443ead-7109-4c23-bdfa-cae65aed12d0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker Compose config

```yaml
name: librenms

services:
  db:
    image: mariadb:10
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MARIADB_RANDOM_ROOT_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./rrd/db:/data/db"
      - "./rrd/journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - redis
      - rrdcached
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always

  dispatcher1:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher1
    hostname: librenms-dispatcher1
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  dispatcher2:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher2
    hostname: librenms-dispatcher2
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher2"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  dispatcher3:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher3
    hostname: librenms-dispatcher3
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher3"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  dispatcher4:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher4
    hostname: librenms-dispatcher4
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher4"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  dispatcher5:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher5
    hostname: librenms-dispatcher5
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher5"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  dispatcher6:
    image: librenms/librenms:latest
    container_name: librenms_dispatcher6
    hostname: librenms-dispatcher6
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher6"
      - "SIDECAR_DISPATCHER=1"
    restart: always

  syslogng:
    image: librenms/librenms:latest
    container_name: librenms_syslogng
    hostname: librenms-syslogng
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    restart: always

  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "./librenms:/data"
    env_file:
      - "./librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SNMPTRAPD=1"
    restart: always

  oxidized:
    restart: always
    image: oxidized/oxidized:latest
    container_name: librenms_oxidized
    hostname: librenms-oxidized
    ports:
      - 8888:8888/tcp
    environment:
      CONFIG_RELOAD_INTERVAL: 600
    volumes:
      - ./oxidized:/home/oxidized/.config/oxidized/
```

### Logs

```text
These are the latest from one of my dispatchers

Billing(INFO):Completed billing run for calculate in 0.47s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.48s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.56s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.50s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.54s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.53s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.48s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.48s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.48s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.69s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.52s
performance(INFO):Counting up time spent polling
Alerting(INFO):Checking alerts
Alerting(INFO):Completed alerting run for alerts in 0.50s
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
Poller_0-7(INFO):Polling device 9
Poller_0-7(INFO):Completed poller run for 9 in 4.36s
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.47s
performance(INFO):Counting up time spent polling
Poller_0-7(INFO):Polling device 7
Poller_0-7(INFO):Completed poller run for 7 in 2.57s
Alerting(INFO):Checking alerts
Alerting(INFO):Completed alerting run for alerts in 0.49s
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
Poller_0-7(INFO):Polling device 9
Poller_0-7(INFO):Completed poller run for 9 in 4.38s
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
Poller_0-15(INFO):Polling device 7
Poller_0-15(INFO):Completed poller run for 7 in 2.59s
performance(INFO):Counting up time spent polling
Poller_0-15(INFO):Polling device 9
Poller_0-15(INFO):Completed poller run for 9 in 4.49s
Billing(INFO):Calculating billing
Billing(INFO):Completed billing run for calculate in 0.45s
Poller_0-15(INFO):Polling device 4
Poller_0-15(INFO):Completed poller run for 4 in 5.89s
performance(INFO):Counting up time spent polling
Billing(INFO):Polling billing
Billing(INFO):Completed billing run for poll in 0.50s
Alerting(INFO):Checking alerts
Alerting(INFO):Completed alerting run for alerts in 0.47s
performance(INFO):Counting up time spent polling
performance(INFO):Counting up time spent polling
```
