### ISSUE TITLE
Poller does not work as of 24.11

### ISSUE THREAD

**Issue by xorrkaz** [librenms/docker#501]
### Support guidelines

- [x] I've read the [support guidelines](https://github.com/librenms/docker/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

As of LibreNMS 24.11, the poller service no longer works.  All devices remain as generic in LibreNMS.  Using 24.10.1 works as expected.  It seems as though the poller underwent several changes to support dispatcher in 24.11, and perhaps this is not reflected in how Docker is built and the dispatcher sidecar is run.  This _might_ be related to #497, but I didn't see the dispatcher service crash/die.

### Expected behaviour

I expect polling to work and devices to be properly discovered.

### Actual behaviour

All devices remain in a generic state.  The logs indicate they are being polled, but their state is not properly reflected in the UI.  What's more alerts are no longer shown in the UI.

### Steps to reproduce

Use docker-compose to start the containers with one container set as a dispatch sidecar.  Our docker-compose.yml is based on the one from the example:

```yaml
version: '3.5'

services:
  db:
    image: mariadb:10.5
    container_name: librenms_db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    volumes:
      - "/var/pii/librenms-mysql:/var/lib/mysql"
    environment:
      - TZ=${TZ}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: librenms_redis
    environment:
      - "TZ=${TZ}"
    restart: always

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: librenms_msmtpd
    env_file:
      - "./msmtpd.env"
    restart: always

  librenms:
    image: billo-librenms
    container_name: librenms
    hostname: librenms
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - db
      - redis
      - msmtpd
    volumes:
      - "/var/pii/librenms:/data"
      - "./lnms-config.yaml:/opt/librenms/database/seeders/config/lnms-config.yaml"
        #- "./Slack.php:/opt/librenms/LibreNMS/Alert/Transport/Slack.php"
        #- "./common.php:/opt/librenms/includes/common.php"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librenms.entrypoints=https"
      - "traefik.http.routers.librenms.rule=Host(`foo`)"
      - "traefik.http.routers.librenms.tls=true"
      - "traefik.http.routers.librenms.tls.certresolver=letsencrypt"
      - "traefik.http.routers.librenms.tls.domains[0].main=foo"
      - "traefik.http.services.librenms.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_TIMEOUT=60
    restart: always
    networks:
      - default
      - proxy

  dispatcher:
    image: billo-librenms
    container_name: librenms_dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms
      - redis
    volumes:
      - "/var/pii/librenms:/data"
      - "./lnms-config.yaml:/opt/librenms/database/seeders/config/lnms-config.yaml"
        #- "./Slack.php:/opt/librenms/LibreNMS/Alert/Transport/Slack.php"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
      - "REDIS_HOST=${REDIS_HOST}"
    restart: always

#  syslogng:
#    image: librenms/librenms:latest
#    container_name: librenms_syslog
#    hostname: librenms-syslogng
#    depends_on:
#      - librenms
#      - redis
#    ports:
#      - target: 514
#        published: 514
#        protocol: tcp
#      - target: 514
#        published: 514
#        protocol: udp
#    volumes:
#      - "./librenms:/data"
#    env_file:
#      - "./librenms.env"
#    environment:
#      - "TZ=${TZ}"
#      - "PUID=${PUID}"
#      - "PGID=${PGID}"
#      - "DB_HOST=db"
#      - "DB_NAME=${MYSQL_DATABASE}"
#      - "DB_USER=${MYSQL_USER}"
#      - "DB_PASSWORD=${MYSQL_PASSWORD}"
#      - "DB_TIMEOUT=60"
#      - "SIDECAR_SYSLOGNG=1"
#    restart: always
#
  snmptrapd:
    image: librenms/librenms:latest
    container_name: librenms_snmptrapd
    hostname: librenms-snmptrapd
    depends_on:
      - librenms
      - redis
    ports:
      - target: 162
        published: 162
        protocol: tcp
      - target: 162
        published: 162
        protocol: udp
    volumes:
      - "/var/pii/librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SNMPTRAPD=1"
    restart: always

networks:
  proxy:
    external: true
```

### Docker info

```text
Client: Docker Engine - Community
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 31
  Running: 16
  Paused: 0
  Stopped: 15
 Images: 115
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: v1.1.14-0-g2c9f560
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-198-generic
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 31.35GiB
 Name: management
 ID: 1a78da55-2504-42b8-b211-c97d3225a2d5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### Docker Compose config

```yaml

```

### Logs

```text
Logs look formal.  For example, we see devices being polled.  One thing that does look suspicious is this:


dispatcher_1  | GigabitEthernet0/0STATIC: Server : vm0STATIC: Server : vm1STATIC: Server : vm2STATIC: Core : RtrHotelASTATIC: Core : TheScoutSTATIC: Core : Son of ScoutSTATIC: Core : RtrNAT64A:ethernet9STATIC: Core : RtrNAT64B:ethernet9TwentyFiveGigE1/0/9TwentyFiveGigE1/0/10STATIC: Core : To WLC-1STATIC: Core : To WLC-2STATIC: Core : To 9800 WLC-1STATIC: Core : To 9800 WLC-2STATIC: Core : RtrA:xe-0/0/0STATIC: Core : RtrB:xe-0/0/0Core : sw-115.meeting.ietf.org:Te1/0/1defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultCore : sw-oob.meeting.ietf.org:Te1/0/1defaultdefaultTwentyFiveGigE1/0/30STATIC: Core : SrxAGeneric : BACKUP-SRX.meeting.ietf.org:530defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultSTATIC: Server : vm0-drbdSTATIC: Server : vm1-drbdSTATIC: Server : vm2-drbddefaultdefaultCore : sw-core3.meeting.ietf.org:Twe1/0/46defaultSTATIC: Core : ###DO NOT TOUCH - VSL DUAL ACTIVE###HundredGigE1/0/49HundredGigE1/0/50STATIC: Core : ###DO NOT TOUCH - VSL LINK###STATIC: Core : ###DO NOT TOUCH - VSL LINK###STATIC: Server : vm0STATIC: Server : vm1STATIC: Server : vm2STATIC: Core : RtrHotelBSTATIC: Core : TheScoutSTATIC: Core : Son of ScoutSTATIC: Core : RtrNAT64A:ethernet9STATIC: Core : RtrNAT64B:ethernet9defaultdefaultSTATIC: Core : To WLC-1STATIC: Core : To WLC-2STATIC: Core : To 9800 WLC-1STATIC: Core : To 9800 WLC-2STATIC: Core : RtrA:xe-0/0/0STATIC: Core : RtrB:xe-0/0/0Core : sw-115.meeting.ietf.org:Te1/0/2defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultCore : sw-oob.meeting.ietf.org:Te1/0/2defaultdefaultTwentyFiveGigE2/0/30STATIC: Core : SrxAGeneric : BACKUP-SRX.meeting.ietf.org:531defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultSTATIC: Server : vm0-drbdSTATIC: Server : vm1-drbdSTATIC: Server : vm2-drbddefaultdefaultCore-to-Spare-CoredefaultSTATIC: Core : ###DO NOT TOUCH - VSL DUAL ACTIVE###HundredGigE2/0/49HundredGigE2/0/50STATIC: Core : ###DO NOT TOUCH - VSL LINK###STATIC: Core : ###DO NOT TOUCH - VSL LINK###Null0Vlan1STATIC: Server : vm0STATIC: Server : vm1STATIC: Server : vm2STATIC: Core : RtrNAT64BSTATIC: Core : RtrNAT64ASTATIC: Core : To WLC-1STATIC: Core : To WLC-2STATIC: Core : RtrA:ae0STATIC: Core : RtrB:ae0STATIC: Core : TheScoutSTATIC: Core : Son Of ScoutdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultSTATIC: Core : SrxA:ae0defaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultdefaultSTATIC: Server : vm0-drbdSTATIC: Server : vm1-drbdSTATIC: Server : vm2-drbddefaultdefaultdefaultVlan224STATIC: Core : To 9800 WLC-1STATIC: Core : To 9800 WLC-2Application: ntp, app_id=2ERROR: /opt/librenms/includes/polling/applications/ntp.inc.php include file missing!
```

**Comment by murrant** [comment]
includes/polling/applications/ntp.inc.php is not a file in LibreNMS, only ntp-client or ntp-server as far as I can tell.

I wonder what is trying to include that?  You could try connecting to the container and run `lnms device:poll -vv <device>`

**Comment by xorrkaz** [comment]
Thanks, Murray.  What I'm seeing is the first time I add a device to a fresh image with a fresh database, it works.  The device is properly learned.  The next time its polled it goes back to a generic device.  And I can't exactly see why.  What I see in the log is this:

```text
#### Load poller module os ####

Module enabled: Global + | OS   | Device   | Manual
SQL[.[1;33mselect exists(select * from `wireless_sensors` where `wireless_sensors`.`device_id` = ? and `wireless_sensors`.`device_id` is not null and `senso
r_class` = ?) as `exists` .[0;33m[1,"ap-count"].[0m 0.79ms]

SQL[.[1;33mselect * from `locations` where `locations`.`id` = ? limit 1 .[0;33m[1].[0m 0.45ms]

Location: Core (MDF)
Hardware: C9500-48Y4C
OS Version: CAT9K_IOSXE 17.12.4
OS Features: Dublin
Serial:
SQL[.[1;33mupdate `devices` set `icon` = ? where `device_id` = ? .[0;33m["generic.svg",1].[0m 1.44ms]

SQL[.[1;33minsert into `eventlog` (`reference`, `type`, `datetime`, `severity`, `message`, `username`, `device_id`) values (?, ?, ?, ?, ?, ?, ?) .[0;33m[nul
l,"system","2025-03-14 15:32:43",3,"Icon: images\/os\/cisco.svg -> images\/os\/generic.svg","",1].[0m 1.34ms]


>> .[0;36mSNMP.[0m: [0/0.00s] .[1;33mMySQL.[0m: [4/0.04s] .[0;32mInfluxDB.[0m: [1/0.00s] .[0;32mRRD.[0m: [2/0.00s]
>> Runtime for poller module 'os': 0.0225 seconds with 166096 bytes
InfluxDB data:  {"measurement":"poller-perf","tags":{"hostname":"sw-core.meeting.ietf.org","module":"os"},"fields":{"poller":0.022533893585205078}}
RRD[.[0;32mcreate /data/rrd/sw-core.meeting.ietf.org/poller-perf-os.rrd --step 60 DS:poller:GAUGE:120:0:U   RRA:AVERAGE:0.5:1:2016 RRA:AVERAGE:0.5:6:1440 RR
A:AVERAGE:0.5:24:1440 RRA:AVERAGE:0.5:288:1440 RRA:MIN:0.5:1:2016 RRA:MIN:0.5:6:1440 RRA:MIN:0.5:24:1440 RRA:MIN:0.5:288:1440 RRA:MAX:0.5:1:2016 RRA:MAX:0.5
:6:1440 RRA:MAX:0.5:24:1440 RRA:MAX:0.5:288:1440 RRA:LAST:0.5:1:2016  -O.[0m]
RRD[.[0;32mupdate /data/rrd/sw-core.meeting.ietf.org/poller-perf-os.rrd N:0.022533893585205.[0m]
#### Unload poller module os ####
```

Why is the OS being changed to generic (essentially, the OS field becomes empty after this and the device gets a generic icon)?

**Comment by xorrkaz** [comment]
I can also provide the full poll -vv output if you want to see it.  I'll also point out that once this problem happens to one device, all subsequent devices will only show as generic until you destroy and recreate the database.

**Comment by xorrkaz** [comment]
Found the problem.  It's not docker-related at all.  We have been using a seeder file to include some initial config.  Part of that file is:

```yaml
os:
    routeros:
        poller_modules:
            netstats: false
```

When doing this in 25.2.0, this replaces _all_ of the "os" block.  In 24.10.1, these changes were merged into the "os" block.  I'll open an issue in the main librenms repo.
