### ISSUE TITLE
Unable to start after upgrade

### ISSUE THREAD

**Issue by Nebucatnetzer** [librenms/docker#58]
I have a working installation however when I do a docker-compose pull and up -d I can't connect anymore to the webinterface. I can see that it is listening on port 80 but I just get the unable to connect message in the browser.
However the logs seem to be okay.

docker-compose.yml

```
version: "3.5"

services:
  db:
    image: mariadb:10.2
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    env_file:
      - "./librenms.env"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    env_file:
      - "./librenms.env"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    env_file:
      - "./librenms.env"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "SERVER_HOSTNAME=librenms.example.com"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    env_file:
      - "./librenms.env"
    restart: always

  librenms:
    image: librenms/librenms
    container_name: librenms
    domainname: 2li.local
    hostname: librenms
    ports:
      - target: 80
        published: 80
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "./librenms:/data"
   environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms
    container_name: librenms_cron
    domainname: 2li.local
    hostname: librenms
    depends_on:
      - librenms
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms
    container_name: librenms_syslog
    domainname: 2li.local
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    restart: always 
```

docker-compose logs
```
ron_1       | crond: crond (busybox 1.30.1) started, log level 8
cron_1       | [services.d] done.
db_1         | 2020-01-22  8:11:07 140434715780416 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2020-01-22  8:11:07 140434715780416 [Note] Server socket created on IP: '::'.
db_1         | 2020-01-22  8:11:07 140434715780416 [Warning] 'proxies_priv' entry '@% root@21013d357906' ignored in --skip-name-resolve mode.
db_1         | 2020-01-22  8:11:07 140434715780416 [Note] Reading of all Master_info entries succeeded
db_1         | 2020-01-22  8:11:07 140434715780416 [Note] Added new Master_info '' to hash table
db_1         | 2020-01-22  8:11:07 140434715780416 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.30-MariaDB-1:10.2.30+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
librenms     | Database ready!
librenms     | Updating database schema...
smtp_1       | Jan 22 08:11:06 57d14c66d525 postfix/postfix-script[96]: starting the Postfix mail system
smtp_1       | Jan 22 08:11:06 57d14c66d525 postfix/master[98]: daemon started -- version 2.10.1, configuration /etc/postfix
librenms     | Nothing to migrate.
librenms     | [cont-init.d] 04-svc-main.sh: exited 0.
librenms     | [cont-init.d] 05-svc-cron.sh: executing...
librenms     | [cont-init.d] 05-svc-cron.sh: exited 0.
librenms     | [cont-init.d] 06-svc-syslogng.sh: executing...
librenms     | [cont-init.d] 06-svc-syslogng.sh: exited 0.
librenms     | [cont-init.d] done.
librenms     | [services.d] starting services
librenms     | [services.d] done.
librenms     | 2020/01/22 08:11:08 [notice] 341#341: using the "epoll" event method
librenms     | 2020/01/22 08:11:08 [notice] 341#341: nginx/1.16.1
librenms     | 2020/01/22 08:11:08 [notice] 341#341: OS: Linux 4.9.0-11-amd64
librenms     | 2020/01/22 08:11:08 [notice] 341#341: getrlimit(RLIMIT_NOFILE): 1048576:1048576
librenms     | 2020/01/22 08:11:08 [notice] 341#341: start worker processes
librenms     | 2020/01/22 08:11:08 [notice] 341#341: start worker process 356
librenms     | 2020/01/22 08:11:08 [notice] 341#341: start worker process 357
librenms     | 2020/01/22 08:11:08 [notice] 341#341: start worker process 358
librenms     | 2020/01/22 08:11:08 [notice] 341#341: start worker process 368
librenms     | [22-Jan-2020 08:11:08] NOTICE: fpm is running, pid 342
librenms     | [22-Jan-2020 08:11:08] NOTICE: ready to handle connections
db_1         | 2020-01-22  8:11:11 140433418090240 [Note] InnoDB: Buffer pool(s) load completed at 200122  8:11:11
cron_1       | crond: USER librenms pid 325 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid 326 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid 327 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid 328 cmd /opt/librenms/discovery.php -h new >> /dev/null 2>&1
cron_1       | crond: USER librenms pid 329 cmd /opt/librenms/alerts.php >> /dev/null 2>&1
cron_1       | crond: USER librenms pid 330 cmd /opt/librenms/poll-billing.php >> /dev/null 2>&1
```
