### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by tnielsen2** [librenms/docker#6]
I am unable to figure out why I am getting a 404 not found error after a fresh install. 

Logs show the following:

```
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] InnoDB: Waiting for purge to start
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] InnoDB: 5.7.24 started; log sequence number 14146729
db_1         | 2018-12-13 10:39:07 140404017821440 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Plugin 'FEEDBACK' is disabled.
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Recovering after a crash using tc.log
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Starting crash recovery...
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Crash recovery finished.
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Server socket created on IP: '::'.
db_1         | 2018-12-13 10:39:07 140404772894656 [Warning] 'proxies_priv' entry '@% root@d8aa15e7c04a' ignored in --skip-name-resolve mode.
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Reading of all Master_info entries succeded
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] Added new Master_info '' to hash table
db_1         | 2018-12-13 10:39:07 140404772894656 [Note] mysqld: ready for connections.
db_1         | Version: '10.2.19-MariaDB-1:10.2.19+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
db_1         | 2018-12-13 10:39:08 140404017821440 [Note] InnoDB: Buffer pool(s) load completed at 181213 10:39:08
traefik_1    | time="2018-12-13T17:39:29Z" level=debug msg="http2: server: error reading preface from client 10.8.2.95:61555: read tcp 172.25.0.6:443->10.8.2.95:61555: read: connection reset by peer"
```

The database is working, and the intial setup script is working as well.

```
sudo docker exec -it dockerlibrenms_app_1 php validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.46
DB Schema | 272
PHP       | 7.2.10
MySQL     | 10.2.19-MariaDB-1:10.2.19+maria~bionic
RRDTool   | 1.7.0
SNMP      | NET-SNMP 5.7.3
====================================

[OK]    Composer Version: 1.8.0
[OK]    Dependencies up-to-date.
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  You have not added any devices yet.
        [FIX]: 
        You can add a device in the webui or with ./addhost.php
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Your install is over 24 hours out of date, last update: Sun, 02 Dec 2018 20:48:18 +0000
        [FIX]: 
        Make sure your daily.sh cron is running and run ./daily.sh by hand to see if there are any errors.
[WARN]  Your local git branch is not master, this will prevent automatic updates.
        [FIX]: 
        You can switch back to master with git checkout master
[FAIL]  We have found some files that are owned by a different user than librenms, this will stop you updating automatically and / or rrd files being updated causing graphs to fail.
        [FIX]: 
        sudo chown -R librenms:librenms /opt/librenms
        sudo setfacl -d -m g::rwx /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        sudo chmod -R ug=rwX /data/rrd /data/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
        Files:
         /opt/librenms/composer.phar
```

.env:
```
DOMAINNAME=OMITTED.com
HOSTNAME=yitydclibrenms

MYSQL_ROOT_PW=OMITTED
MYSQL_DATABASE=librenms
MYSQL_USER=sa-librenms
MYSQL_PASSWORD=OMITTED

SMTP_SERVER=relay.OMITTED.com
SMTP_USERNAME=''
SMTP_PASSWORD=''

TZ=OMITTED
PUID=1000
PGID=1000
```

librenms.env:
```
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128

LIBRENMS_POLLER_THREADS=16
LIBRENMS_POLLER_INTERVAL=5

LIBRENMS_CRON_DISCOVERY_ENABLE=true
LIBRENMS_CRON_DAILY_ENABLE=true
LIBRENMS_CRON_ALERTS_ENABLE=true
LIBRENMS_CRON_BILLING_ENABLE=true
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true
LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true
LIBRENMS_CRON_POLLER_ENABLE=true

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217
```

docker-compose.yml:

```
version: "3.2"

services:
  traefik:
    image: traefik:1.6-alpine
    command:
      - "--api"
      - "--logLevel=DEBUG"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=${DOMAINNAME}"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@example.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  db:
    image: mariadb:10.2
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
    volumes:
      - "/var/lib/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - "SERVER_HOSTNAME=${HOSTNAME}.${DOMAINNAME}"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    restart: always

  app:
    image: librenms/librenms:latest
    domainname: ${DOMAINNAME}
    hostname: ${HOSTNAME}
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "/opt/docker-librenms:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=librenms"
      - "traefik.port=80"
      - "traefik.frontend.rule=${HOSTNAME}"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms:latest
    domainname: ${DOMAINNAME}
    hostname: ${HOSTNAME}
    command:
      - "/usr/local/bin/cron"
    depends_on:
      - app
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    domainname: ${DOMAINNAME}
    hostname: ${HOSTNAME}
    command:
      - "/usr/sbin/syslog-ng"
      - "-F"
    depends_on:
      - app
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=30"
    env_file:
      - "./librenms.env"
    restart: always
```

**Comment by crazy-max** [comment]
@tnielsen2 Are ports 80 / 443 / 8080 available on your hosts ?
And also you can remove 8080 port binding.

**Comment by tnielsen2** [comment]
I have tried both ways. Initially I had 8080 off, as per your config, but added it with the api to see the dashboard.

**Comment by crazy-max** [comment]
@tnielsen2 Seems related to ACME. Is your host available on WAN ?

Try this :

```
traefik:
    image: traefik:1.6-alpine
    command:
      - "--api"
      - "--logLevel=DEBUG"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=${DOMAINNAME}"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
```
