### ISSUE TITLE
Fresh install gives broken login page - "Cannot write to log file".

### ISSUE THREAD

**Issue by scline** [librenms/docker#66]
### Behaviour

After a fresh install using docker-compose Librenms comes up broken with the error
```
Running the following commands will fix the issue most of the time:
Cannot write to log file: "/data/logs/librenms.log"
Make sure it exists and is writable, or change your LOG_DIR setting.

If using SELinux you may also need:
semanage fcontext -a -t httpd_sys_rw_content_t '/data/logs/librenms.log(/.*)?'

restorecon -RFv /data/logs/librenms.log
```

When running the validate.php script, it complains that the database needs to be migrated
```
root@librenms:/opt/librenms/logs# docker exec -it librenms ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.62.2
DB Schema | No Schema (0)
PHP       | 7.3.14
MySQL     | 10.2.31-MariaDB-1:10.2.31+maria~bionic
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[FAIL]  Your database is out of date!
	[FIX]:
	./lnms migrate
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

Log file permission before running `./lnms migrate`
```
root@librenms:/opt/librenms/logs# ls -alh
total 108K
drwxrwxr-x 2 librenms librenms 4.0K Apr 12 09:59 .
drwxr-xr-x 9 librenms librenms 4.0K Apr 12 09:59 ..
-rw-r--r-- 1 root     root      99K Apr 12 10:01 librenms.log
```

Log file permissions and validate output after running `./lnms migrate`

```
root@librenms:/opt/librenms/logs# ls -alh
total 264K
drwxrwxr-x 2 librenms librenms 4.0K Apr 12 09:59 .
drwxr-xr-x 9 librenms librenms 4.0K Apr 12 09:59 ..
-rw-r--r-- 1 root     root     255K Apr 12 10:03 librenms.log


root@librenms:/opt/librenms/logs# docker exec -it librenms ./validate.php
====================================
Component | Version
--------- | -------
LibreNMS  | 1.62.2
DB Schema | 2020_03_24_0844_add_primary_key_to_device_graphs (160)
PHP       | 7.3.14
MySQL     | 10.2.31-MariaDB-1:10.2.31+maria~bionic
RRDTool   | 1.7.2
SNMP      | NET-SNMP 5.8
====================================

[OK]    Installed from the official Docker image; no Composer required
[OK]    Database connection successful
[OK]    Database schema correct
[WARN]  IPv6 is disabled on your server, you will not be able to add IPv6 devices.
[WARN]  Updates are managed through the official Docker image
```

The login screen works after running the migration command.

#### Steps to reproduce this issue

1. Fresh install using provided docker-compose file in repo

#### Expected behaviour

After install navigate to a working login screeen

#### Actual behaviour

Get a webpage reporting `Cannot write to log file: "/data/logs/librenms.log"`

### Configuration

* Docker version: `Docker version 19.03.8, build afacb8b7f0`
* Docker compose version: `docker-compose version 1.17.1, build unknown`
* Platform : `Ubuntu 18.04`
* System info: `Linux librenms 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

**librenms.env**
```
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

LIBRENMS_POLLER_THREADS=2
LIBRENMS_POLLER_INTERVAL=5

LIBRENMS_CRON_DISCOVERY_ENABLE=true
LIBRENMS_CRON_DAILY_ENABLE=true
LIBRENMS_CRON_ALERTS_ENABLE=true
LIBRENMS_CRON_BILLING_ENABLE=true
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true
LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true
LIBRENMS_CRON_POLLER_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_NETS=10.1.0.0/16,10.2.0.0/16
LIBRENMS_CRON_SNMPSCAN_LOGFILE=/data/logs/snmp-scan.log

LIBRENMS_SNMP_COMMUNITY=*****
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217
```

**docker-compose.yml**
```
version: "3.5"

services:
  db:
    image: mariadb:10.2
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "/opt/librenms/db:/var/lib/mysql"
    environment:
      - "TZ=America/Los_Angeles"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=librenms"
      - "MYSQL_USER=librenms"
      - "MYSQL_PASSWORD=*****"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=America/Los_Angeles"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "/opt/librenms/rrd:/data/db"
      - "/opt/librenms/rrd-journal:/data/journal"
    environment:
      - "TZ=America/Los_Angeles"
      - "PUID=1337"
      - "PGID=1337"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    environment:
      - "SERVER_HOSTNAME=librenms.example.com"
      - "SMTP_SERVER=*****"
      - "SMTP_USERNAME=*****"
      - "SMTP_PASSWORD=*****"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    domainname: example.com
    hostname: librenms
    ports:
      - target: 8000
        published: 80
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "/opt/librenms:/data"
    environment:
      - "TZ=America/Los_Angeles"
      - "PUID=1337"
      - "PGID=1337"
      - "DB_HOST=db"
      - "DB_NAME=librenms"
      - "DB_USER=librenms"
      - "DB_PASSWORD=*****"
      - "DB_TIMEOUT=60"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms:latest
    container_name: librenms_cron
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    volumes:
      - "/opt/librenms:/data"
    environment:
      - "TZ=America/Los_Angeles"
      - "PUID=1337"
      - "PGID=1337"
      - "DB_HOST=db"
      - "DB_NAME=librenms"
      - "DB_USER=librenms"
      - "DB_PASSWORD=*****"
      - "DB_TIMEOUT=60"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    container_name: librenms_syslog
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "/opt/librenms:/data"
    environment:
      - "TZ=America/Los_Angeles"
      - "PUID=1337"
      - "PGID=1337"
      - "DB_HOST=db"
      - "DB_NAME=librenms"
      - "DB_USER=librenms"
      - "DB_PASSWORD=*****"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    restart: always
```

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 6
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-96-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.853GiB
 Name: librenms
 ID: DTSS:WIXD:TGOQ:NSIT:VLEE:4QN5:5RLB:I365:OHNF:ETIY:P7FH:IBZB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```
