### ISSUE TITLE
Devices "never polled"

### ISSUE THREAD

**Issue by ggdagg** [librenms/docker#69]
### Behaviour
All my devices are shown with the state "Never polled" in the Up/Down Time column in LibreNMS web interface on Devices/All Devices page. Even localhost (=127.0.0.1) has this same state.

#### Steps to reproduce this issue

1. docker-composer up -d
2. Log into LibreNMS via the web interface
3. Add a new device "localhost" with the SNMP community "librenmsdocker"
4. Wait 10 minutes

#### Expected behaviour

I would expect to see the uptime of the device monitored in the column Up/Down Time on the page Devices/All Devices.

#### Actual behaviour

Instead of seeing the device's uptime, "Never polled" is displayed in the column Up/Down Time of the page Devices/All Devices.

### Configuration

* Docker version : Docker version 19.03.8, build afacb8b
* Docker compose version if applicable : docker-compose version 1.25.5, build 8a1c60f6
* Platform : CentOS Linux release 7.7.1908 (Core)
* System info : Linux EGNMS02 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

.env

```
MYSQL_DATABASE=librenms
MYSQL_USER=librenms
MYSQL_PASSWORD=asupersecretpassword

SMTP_SERVER=smtp.example.com
SMTP_USERNAME=smtp@example.com
SMTP_PASSWORD=

TZ=Europe/Paris
PUID=1000
PGID=1000
```

librenms.env
```
MEMORY_LIMIT=256M
UPLOAD_MAX_SIZE=16M
OPCACHE_MEM_SIZE=128
REAL_IP_FROM=0.0.0.0/32
REAL_IP_HEADER=X-Forwarded-For
LOG_IP_VAR=remote_addr

LIBRENMS_POLLER_THREADS=16
LIBRENMS_POLLER_INTERVAL=5

LIBRENMS_CRON_DISCOVERY_ENABLE=true
LIBRENMS_CRON_DAILY_ENABLE=true
LIBRENMS_CRON_ALERTS_ENABLE=true
LIBRENMS_CRON_BILLING_ENABLE=true
LIBRENMS_CRON_BILLING_CALCULATE_ENABLE=true
LIBRENMS_CRON_CHECK_SERVICES_ENABLE=true
LIBRENMS_CRON_POLLER_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_ENABLE=true
LIBRENMS_CRON_SNMPSCAN_NETS=192.168.0.0/24,192.168.1.0/24
LIBRENMS_CRON_SNMPSCAN_LOGFILE=/data/logs/snmp-scan.log

LIBRENMS_SNMP_COMMUNITY=librenmsdocker
MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
RRDCACHED_HOST=rrdcached
RRDCACHED_PORT=42217
```

docker-compose.yml
```
version: "3.5"

services:
  db:
    image: mariadb:10.2
    container_name: librenms_db
    command:
      - "mysqld"
      - "--sql-mode="
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=0"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "./db:/var/lib/mysql"
    environment:
      - "TZ=${TZ}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USER}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    restart: always

  memcached:
    image: memcached:alpine
    container_name: librenms_memcached
    environment:
      - "TZ=${TZ}"
    restart: always

  rrdcached:
    image: crazymax/rrdcached
    container_name: librenms_rrdcached
    volumes:
      - "./librenms/rrd:/data/db"
      - "./rrd-journal:/data/journal"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "LOG_LEVEL=LOG_INFO"
      - "WRITE_TIMEOUT=1800"
      - "WRITE_JITTER=1800"
      - "WRITE_THREADS=4"
      - "FLUSH_DEAD_DATA_INTERVAL=3600"
    restart: always

  smtp:
    image: juanluisbaptiste/postfix
    container_name: librenms_smtp
    environment:
      - "SERVER_HOSTNAME=librenms.example.com"
      - "SMTP_SERVER=${SMTP_SERVER}"
      - "SMTP_USERNAME=${SMTP_USERNAME}"
      - "SMTP_PASSWORD=${SMTP_PASSWORD}"
    restart: always

  librenms:
    image: librenms/librenms:latest
    container_name: librenms
    domainname: example.com
    hostname: librenms
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    depends_on:
      - db
      - memcached
      - rrdcached
      - smtp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
    env_file:
      - "./librenms.env"
    restart: always

  cron:
    image: librenms/librenms:latest
    container_name: librenms_cron
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_CRON=1"
    env_file:
      - "./librenms.env"
    restart: always

  syslog-ng:
    image: librenms/librenms:latest
    container_name: librenms_syslog
    domainname: example.com
    hostname: librenms
    depends_on:
      - librenms
    ports:
      - target: 514
        published: 514
        protocol: tcp
      - target: 514
        published: 514
        protocol: udp
    volumes:
      - "./librenms:/data"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=db"
      - "DB_NAME=${MYSQL_DATABASE}"
      - "DB_USER=${MYSQL_USER}"
      - "DB_PASSWORD=${MYSQL_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "SIDECAR_SYSLOGNG=1"
    env_file:
      - "./librenms.env"
    restart: always
```

### Docker info

```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 6
  Paused: 0
  Stopped: 1
 Images: 5
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1062.18.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.638GiB
 Name: EGNMS02
 ID: 4VOK:WTCA:OXZL:VEQJ:UNRL:VSD5:BHDH:EIUI:UOTK:AIC7:ELP4:VXON
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Logs

tail librenms/logs/librenms.log

```
/opt/librenms/discovery.php new 2020-04-23 18:05:14 - 0 devices discovered in 13.10 secs
/opt/librenms/poller.php 1 2020-04-23 18:05:15 - 1 devices polled in 13.16 secs
/opt/librenms/discovery.php new 2020-04-23 18:10:15 - 0 devices discovered in 13.10 secs
/opt/librenms/poller.php 1 2020-04-23 18:10:15 - 1 devices polled in 13.16 secs
/opt/librenms/discovery.php new 2020-04-23 18:15:15 - 0 devices discovered in 13.12 secs
/opt/librenms/poller.php 1 2020-04-23 18:15:15 - 1 devices polled in 13.17 secs
/opt/librenms/discovery.php new 2020-04-23 18:20:15 - 0 devices discovered in 13.11 secs
/opt/librenms/poller.php 1 2020-04-23 18:20:15 - 1 devices polled in 13.16 secs
/opt/librenms/discovery.php new 2020-04-23 18:25:15 - 0 devices discovered in 13.10 secs
/opt/librenms/poller.php 1 2020-04-23 18:25:15 - 1 devices polled in 13.16 secs

```

docker container ps -a
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                          PORTS                                                  NAMES
b0e2df5dbf95        librenms/librenms:latest   "/init"                  25 hours ago        Up 25 hours                     514/tcp, 8000/tcp, 514/udp                             librenms_cron
9b955eb6a02b        librenms/librenms:latest   "/init"                  25 hours ago        Up 25 hours                     0.0.0.0:514->514/tcp, 0.0.0.0:514->514/udp, 8000/tcp   librenms_syslog
5555b392b76f        librenms/librenms:latest   "/init"                  25 hours ago        Up 25 hours                     514/tcp, 514/udp, 0.0.0.0:8000->8000/tcp               librenms
71bf929c8b5d        memcached:alpine           "docker-entrypoint.s…"   25 hours ago        Up 25 hours                     11211/tcp                                              librenms_memcached
8310d5276d21        juanluisbaptiste/postfix   "/run.sh"                25 hours ago        Restarting (1) 59 seconds ago                                                          librenms_smtp
a3cbce6419ca        crazymax/rrdcached         "/entrypoint.sh /usr…"   25 hours ago        Up 25 hours (healthy)           42217/tcp                                              librenms_rrdcached
1e50c5704c15        mariadb:10.2               "docker-entrypoint.s…"   25 hours ago        Up 25 hours                     3306/tcp                                               librenms_db
```

```
[root@EGNMS02 librenms]# docker exec -it librenms sh
/opt/librenms # snmpwalk -mALL -v2c -c librenmsdocker localhost
SNMPv2-MIB::sysDescr.0 = STRING: Linux librenms 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-TC::linux
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (9166587) 1 day, 1:27:45.87
SNMPv2-MIB::sysContact.0 = STRING: Your Name <your@email.address>
SNMPv2-MIB::sysName.0 = STRING: librenms
SNMPv2-MIB::sysLocation.0 = STRING: Rack, Room, Building, City, Country [GPSX,Y]
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (1) 0:00:00.01
SNMPv2-MIB::sysORID.1 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.2 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.5 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.6 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.7 = OID: IP-MIB::ip
SNMPv2-MIB::sysORID.8 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
SNMPv2-MIB::sysORID.10 = OID: NOTIFICATION-LOG-MIB::notificationLogMIB
SNMPv2-MIB::sysORDescr.1 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.2 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.3 = STRING: The management information definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.5 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing TCP implementations
SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing IP and ICMP implementations
SNMPv2-MIB::sysORDescr.8 = STRING: The MIB module for managing UDP implementations
SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP Notification, plus filtering.
SNMPv2-MIB::sysORDescr.10 = STRING: The MIB module for logging SNMP Notifications.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
[...]
```

Please let me know if I need to provide with anything else.
Thank you for your help.
