### ISSUE TITLE
RRD files not updating with dispatcher on k3s

### ISSUE THREAD

**Issue by mzac** [librenms/docker#97]
### Behaviour
I'm running my LibreNMS setup in k3s.  I converted my cron deployment to use dispatcher instead.  Everything looks good, no errors in logs, they show up in the gui (using a stateful set of 3 dispatchers) however none of the RRD files are getting updated.

I have tried to turn on debugging through the gui for the dispatcher but it doesn't seem to take effect in the container logs.

#### Steps to reproduce this issue

1. Convert cron to dispatcher
2. Check librenms, still talking to devices but no rrd updates

#### Expected behaviour

RRDs should be updated

#### Actual behaviour

RRDs are not updated

### Configuration

* Docker version (type `docker --version`) : K3S v1.17.6+k3s1
* Platform (Debian 9, Ubuntu 18.04, ...) : Ubuntu 18.04
* System info (type `uname -a`) : Linux k3s-vm2 4.15.0-109-generic #110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Include all necessary configuration files : `docker-compose.yml`, `.env`, ...

```
# --------------------------------------------------------------------------------
# LibreNMS Dispatcher
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: librenms-dispatcher
  namespace: librenms
spec:
  serviceName: librenms-dispatcher
  replicas: 3
  selector:
    matchLabels:
      app: librenms-dispatcher
  template:
    metadata:
      labels:
        app: librenms-dispatcher
    spec:
      initContainers:
        - name: nfs-fixer
          image: alpine
          securityContext:
            runAsUser: 0
          volumeMounts:
          - name: librenms-data
            mountPath: /nfs
          command:
          - sh
          - -c
          - (chmod 0775 /nfs; chown -R 1000:1000 /nfs)
      containers:
      - name: librenms-dispatcher
        image: librenms/librenms:1.65
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: America/Montreal
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: librenms-config
              key: MYSQL_PASSWORD
        - name: DB_TIMEOUT
          value: "60"
        - name: DISPATCHER_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: SIDECAR_DISPATCHER
          value: "1"
        volumeMounts:
        - name: librenms-data
          mountPath: /data
      nodeSelector:
        kubernetes.io/arch: amd64
        node-role.kubernetes.io/vm: ""
      volumes:
      - name: librenms-data
        nfs:
          server: 192.168.0.6
          path: /volume1/k3s/librenms/librenms-data
```

```
NAME                         READY   STATUS    RESTARTS   AGE     IP            NODE      NOMINATED NODE   READINESS GATES
memcached-dcf8f5db4-9vrvg    1/1     Running   0          151m    10.42.6.185   k3s-vm2   <none>           <none>
redis-569dbd4f8c-26vg8       1/1     Running   0          151m    10.42.6.186   k3s-vm2   <none>           <none>
rrdcached-85fbbcc446-zr5gt   1/1     Running   0          151m    10.42.6.187   k3s-vm2   <none>           <none>
librenms-9bfb496bc-4btfm     1/1     Running   0          100m    10.42.3.108   k3s-vm4   <none>           <none>
librenms-9bfb496bc-44mqf     1/1     Running   0          100m    10.42.6.190   k3s-vm2   <none>           <none>
librenms-dispatcher-0        1/1     Running   0          9m37s   10.42.3.111   k3s-vm4   <none>           <none>
librenms-dispatcher-1        1/1     Running   0          68s     10.42.6.192   k3s-vm2   <none>           <none>
librenms-dispatcher-2        1/1     Running   0          63s     10.42.5.206   k3s-vm3   <none>           <none>
```

![image](https://user-images.githubusercontent.com/10270879/86619910-668a8400-bf89-11ea-8114-83f0ae827f68.png)
